### PR TITLE
Upgrade to Swift 3.0

### PR DESCRIPTION
**Pull request by DK1DA**

### CODE REVIEW

**Comment by spxrogers** [comment]
hi @kimar, thanks for the PR to support this project. i am confused, however—the version 2.0 release added Swift 3 support.

**Comment by DK1DA** [comment]
Hey, when trying to build the RxMoyaGloss the build tool doesn't compile because the Swift version isn't set. If just ran the migration tool, the actual code changes shouldn't be necessary though.

Additionally I'm having issues using the RxMoyaGloss target with Carthage. It fails when trying to clean the build, haven't looked at the xcodebuild output yet. Keeps this PR open and I'll double check and get back to you.

**Comment by spxrogers** [comment]
peculiar, haven't experienced that behavior. 

can you also provide the following:
  - xcode version
  - swift version
  - carthage version
  - cartfile (only relevant parts necessary)
  - error messages

and i'll look into it!

**Comment by DK1DA** [comment]
Sorry just double checked and it indeed seems as if my probem is related to an upgrade that occurred on Moya.

```
SignalProducer+Gloss.swift:49:88: error: 'Error' has been renamed to 'MoyaError': Moya.Error has
```

**Pull request closed without merging**
